### ISSUE TITLE
web service infrastructure 

### ISSUE THREAD

**Issue by realabdu** [linuxscout/yarob#21]
السلام عليكم د.طه
استطعت تشغيل المشروع في بيئة التطير المحلية بنجاح، لدي مجموعة استفسارات بخصوص معمارية الويب الموجودة حاليا بالمشروع،
لماذا تم فصل الواجهة الأمامية والخلفية بالشكل الموجود الان ؟ 
اعذرني سأكتب بالانقليزي لتوضيح الكلمات التقنية 

index.html of web frontend makes an ajax request to the flask server, through the getAjax endpoint. that endpoint calls adaat.

why are we separating this functionality?
 we can implement that frontend within the Flask server, and the code would be reduced.

**Comment by linuxscout** [comment]
السلام عليكم،
أدرك أنني يمكن أستعمل فلاسك في كل المراحل،
أردت أن أفضلها إلى واجهتين، لتسهيل تصميم تطبيق مستقبلا يعتمد على الAPI الخاصة بالمشروع،
من جانب آخر، أستفيد من تصميم الواجهة النهائية من طرف آخر، دون تفاصيل الخدمة الأساسية

**Comment by abdullahmosaibah** [comment]
واضح، 
هل تعتقد انه فلاسك أفضل خيار لكشف مجموعة endpoints  ؟
من الممكن تحقيق الهدف بشكل أبسط لو استعملنا fastapi 

وذلك سيسهل الوصول لخدمات المشروع

**Comment by linuxscout** [comment]
شكرا لك،
ممكن استعمال fastَAPI إذا كان خيارًا أفضل،
لم أجربه على خادم الوب عند المستضيف

**Comment by abdullahmosaibah** [comment]
ممتاز، سأجرب ذلك

**Comment by abdullahmosaibah** [comment]
بأمكانك متابعة العمل هنا
https://github.com/linuxscout/yarob/pull/22
